### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DaAnEr80** [AbcAeffchen/sudoku-php#1]
It looks like "self::EASY" and "self::VERY_EASY" does not work.

**Comment by AbcAeffchen** [comment]
The issue is resolved but the tests are not running due to version problems. Either the php version is to old or the PHPUnit is to old or the Tests are written for an old PHPUnit version... I will fix the tests sometime else. In the mean time you can use the current master branch (dev-master in composer) for for the fixed version.
